language: scala

scala:
   - 2.10.5
   - 2.11.6

sbt_args: -no-colors

env:
   global:
      - JVM_OPTS="-XX:MaxPermSize=256m -Xmx1024m -XX:ReservedCodeCacheSize=128m"

script: sbt ++$TRAVIS_SCALA_VERSION  clean coveralls coverage test coverageReport coverageAggregate codacyCoverage


jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

notifications:
  email:
     recipients:
      - github@crossing-tech.com
     on_success: never  #default: change
     on_failure: always #default: always
  irc: "irc.codehaus.org#babel" 
