language: java

global:
   env:
     - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx1024m"

install: mvn -Parchetype -Preformat -DskipTests clean install

script:
   - mvn -Parchetype  test
   - .travis/reformat.sh

jdk:
   - openjdk6

notifications:
  email:
     recipients:
      - github@crossing-tech.com
     on_success: never  #default: change
     on_failure: always #default: always
  irc: "irc.codehaus.org#babel"   
