language: scala

scala:
   - 2.10.4
   - 2.11.2

sbt_args: -no-colors

env:
   global:
      - SBT_OPTS="-XX:MaxPermSize=256m -Xmx1024m"

script:  
   - sbt ++$TRAVIS_SCALA_VERSION "set camelVersion := \"2.12.4\"" test
   - sbt coveralls


jdk:
  - openjdk6


notifications:
  email:
     recipients:
      - github@crossing-tech.com
     on_success: never  #default: change
     on_failure: always #default: always
  irc: "irc.codehaus.org#babel" 
